function mainRouter(app, db, io) {

    /////////////////////////////// ACCOUNT ROUTER STARTS ////////////////////////////////


    const employee = require(__dirname + '/daHrRouter/employee.js')
    const designation = require(__dirname + '/daHrRouter/designation.js')
    const department = require(__dirname + '/daHrRouter/department.js')
    const workingPlace = require(__dirname + '/daHrRouter/workingPlace.js')
    const employeeType = require(__dirname + '/daHrRouter/employeeType.js')
    const religion = require(__dirname + '/daHrRouter/religion.js')
    const bloodGroup = require(__dirname + '/daHrRouter/bloodGroup.js')
    const dutyShift = require(__dirname + '/daHrRouter/dutyShift.js')
    const address = require(__dirname + '/daHrRouter/address.js')
    const addressType = require(__dirname + '/daHrRouter/addressType.js')
    const village = require(__dirname + '/daHrRouter/village.js')
    const postOffice = require(__dirname + '/daHrRouter/postOffice.js')
    const policeStation = require(__dirname + '/daHrRouter/policeStation.js')
    const district = require(__dirname + '/daHrRouter/district.js')
    const referer = require(__dirname + '/daHrRouter/referer.js')
    const education = require(__dirname + '/daHrRouter/education.js')
    const experience = require(__dirname + '/daHrRouter/experience.js')
    const salary = require(__dirname + '/daHrRouter/salary.js')
    const attendence = require(__dirname + '/daHrRouter/attendence.js')
    const user = require(__dirname + '/daHrRouter/user.js')
    const leaveType = require(__dirname + '/daHrRouter/leaveType.js')
    const leave = require(__dirname + '/daHrRouter/leave.js')
    const holiday = require(__dirname + '/daHrRouter/holiday.js')
    const adjustment = require(__dirname + '/daHrRouter/adjustment.js')
    const workTime = require(__dirname + '/daHrRouter/workTime.js')
    const voucherType = require(__dirname + '/daHrRouter/voucherType.js')
    const voucher = require(__dirname + '/daHrRouter/voucher.js')
    const status = require(__dirname + '/daHrRouter/status.js')
    const paymentStatus = require(__dirname + '/daHrRouter/paymentStatus.js')
    const paymentType = require(__dirname + '/daHrRouter/paymentType.js')
    const accountsType = require(__dirname + '/daHrRouter/accountsType.js')
    const accountsHead = require(__dirname + '/daHrRouter/accountsHead.js')
    const subHead = require(__dirname + '/daHrRouter/subHead.js')
    const section = require(__dirname + '/daHrRouter/section.js')
    const promotion = require(__dirname + '/daHrRouter/promotion.js')
    const monthlySummary = require(__dirname + '/daHrRouter/monthlySummary.js')
    const monthlyPayment = require(__dirname + '/daHrRouter/monthlyPayment.js')
    const punchProblem = require(__dirname + '/daHrRouter/punchProblem.js')
    const bank = require(__dirname + '/daHrRouter/bank.js')
    const deduction = require(__dirname + '/daHrRouter/deduction.js')
    const monthlyAttendance = require(__dirname + '/daHrRouter/monthlyAttendance.js')
    const overTimeSummary = require(__dirname + '/daHrRouter/overTimeSummary.js')
    const comparative = require(__dirname + '/daHrRouter/comparative.js')
    const production = require(__dirname + '/daHrRouter/production.js')
    const getController = require(__dirname + '/daHrRouter/getController.js')

    employee.routerInit(app, db)
    designation.routerInit(app, db)
    department.routerInit(app, db)
    workingPlace.routerInit(app, db)
    employeeType.routerInit(app, db)
    religion.routerInit(app, db)
    bloodGroup.routerInit(app, db)
    dutyShift.routerInit(app, db)
    address.routerInit(app, db)
    addressType.routerInit(app, db)
    village.routerInit(app, db)
    postOffice.routerInit(app, db)
    policeStation.routerInit(app, db)
    district.routerInit(app, db)
    referer.routerInit(app, db)
    education.routerInit(app, db)
    experience.routerInit(app, db)
    salary.routerInit(app, db)
    attendence.routerInit(app, db)
    user.routerInit(app, db)
    leaveType.routerInit(app, db)
    leave.routerInit(app, db)
    holiday.routerInit(app, db)
    adjustment.routerInit(app, db)
    workTime.routerInit(app, db)
    voucherType.routerInit(app, db)
    voucher.routerInit(app, db)
    status.routerInit(app, db)
    paymentStatus.routerInit(app, db)
    paymentType.routerInit(app, db)
    accountsType.routerInit(app, db)
    accountsHead.routerInit(app, db)
    subHead.routerInit(app, db)
    section.routerInit(app, db)
    promotion.routerInit(app, db)
    monthlySummary.routerInit(app, db)
    monthlyPayment.routerInit(app, db)
    punchProblem.routerInit(app, db)
    bank.routerInit(app, db)
    deduction.routerInit(app, db)
    monthlyAttendance.routerInit(app, db)
    overTimeSummary.routerInit(app, db)
    comparative.routerInit(app, db)
    production.routerInit(app, db)
    getController.routerInit(app, db)

    io.on('connection', function(s) {
        employee.socketInit(db, s)
        designation.socketInit(db, s)
        department.socketInit(db, s)
        workingPlace.socketInit(db, s)
        employeeType.socketInit(db, s)
        religion.socketInit(db, s)
        bloodGroup.socketInit(db, s)
        dutyShift.socketInit(db, s)
        address.socketInit(db, s)
        addressType.socketInit(db, s)
        village.socketInit(db, s)
        postOffice.socketInit(db, s)
        policeStation.socketInit(db, s)
        district.socketInit(db, s)
        referer.socketInit(db, s)
        education.socketInit(db, s)
        experience.socketInit(db, s)
        salary.socketInit(db, s)
        attendence.socketInit(db, s)
        user.socketInit(db, s)
        leaveType.socketInit(db, s)
        leave.socketInit(db, s)
        holiday.socketInit(db, s)
        adjustment.socketInit(db, s)
        workTime.socketInit(db, s)
        voucherType.socketInit(db, s)
        voucher.socketInit(db, s)
        status.socketInit(db, s)
        paymentStatus.socketInit(db, s)
        paymentType.socketInit(db, s)
        accountsType.socketInit(db, s)
        accountsHead.socketInit(db, s)
        subHead.socketInit(db, s)
        section.socketInit(db, s)
        promotion.socketInit(db, s)
        monthlySummary.socketInit(db, s)
        monthlyPayment.socketInit(db, s)
        punchProblem.socketInit(db, s)
        bank.socketInit(db, s)
        deduction.socketInit(db, s)
        monthlyAttendance.socketInit(db, s)
        overTimeSummary.socketInit(db, s)
        comparative.socketInit(db, s)
        production.socketInit(db, s)
        getController.socketInit(db, s)
    })

    /////////////////////////////// ACCOUNT ROUTER ENDS ////////////////////////////////

}

module.exports.mainRouter = mainRouter;